pipeline:
  name: deploy
  identifier: deploy
  projectIdentifier: Devopsnow
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: AKS
              namespace: maven-app
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker
                    repo: smr1234/maven
                    tags:
                      - latest
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1741324575330
        repoName: Shashank78351/maven
        build: <+input>
