environment:
  name: dev
  identifier: dev
  orgIdentifier: default
  projectIdentifier: Devopsnow
  description: ""
  tags: {}
  type: PreProduction
  yaml: |
    environment:
      name: ""
      identifier: ""
      orgIdentifier: default
      projectIdentifier: Devopsnow
      description: ""
      tags: {}
      type: ""
