apiVersion:
kind:
metadata:
  namespace:
  name:
  labels:
    app:
spec:
  replicas:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image:
        ports:
        - containerPort:
      imagePullSecrets:
      - name:
