apiVersion: v1
kind: Service
metadata:
  namespace: maven-app
  name: maven-service
  labels:
    app: maven
spec:
  selector:
    app: maven
  ports:
    - name: maven-service
      protocol: TCP
      port: 80
      targetPort: 8092 
  type: NodePort

