name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux-1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: 'adopt'
    #     java-version: '11'

    # - name: Cache Maven packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.m2/repository
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: ${{ runner.os }}-maven

    # - name: Build
    #   run: mvn -B package --file pom.xml

    # - name: Run tests
    #   run: mvn test

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=smr123/maven
        IMAGE_TAG=${GITHUB_RUN_NUMBER}
        docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG --label "runnumber=${GITHUB_RUN_ID}"
        docker push $IMAGE_NAME:$IMAGE_TAG
    
  update-manifest:
    runs-on: [self-hosted, linux-1]
    needs: ['build']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Shashank78351/maven
          ref: 'master'
          token: ${{ secrets.TOKEN }}
      - name: Set up Git config
        run: |
            git config --global user.email "shashankmr170@gmail.com"
            git config --global user.name "Shashank78351"
    
      - name: Update deployment YAML
        run: |
            sed -i "s#${{ needs.build.outputs.IMAGE_NAME }}.*#${{ needs.build.outputs.IMAGE_NAME }}:${{ needs.build.outputs.IMAGE_TAG }}#g" kube/deployment.yml
    
      - name: Add changes and commit
        run: |
            git add kube/deployment.yml
            git commit -m "Update image to ${{ needs.build.outputs.IMAGE_NAME }}:${{ needs.build.outputs.IMAGE_TAG }}"
    
      - name: Push changes to repository
        run: |
            git push origin master